### ISSUE TITLE
Is birthday getting mixed up, or is it formatting oddly?

### ISSUE THREAD

**Issue by bencentra** [JDrit/profiles#29]
I update my birthday.

![screen shot 2015-01-16 at 9 35 11 am](https://cloud.githubusercontent.com/assets/517104/5777720/24ad2c84-9d63-11e4-95c9-c69d55fa3900.png)

I click "Done". Birthday is as I typed it.

![screen shot 2015-01-16 at 9 35 31 am](https://cloud.githubusercontent.com/assets/517104/5777727/3887ca02-9d63-11e4-9767-05b3cbc6edf7.png)

I refresh the page. Birthday (formatting) has changed.

![screen shot 2015-01-16 at 9 35 37 am](https://cloud.githubusercontent.com/assets/517104/5777734/463ea652-9d63-11e4-8744-3e126812c7f3.png)

**Comment by JDrit** [comment]
Fixed, I was parsing the date wrong.
