### ISSUE TITLE
Formatting in lynx isn't great

### ISSUE THREAD

**Issue by dgonyeo** [JDrit/profiles#30]
When profiles is viewed via lynx, the formatting could use some work.

![profiles](https://cloud.githubusercontent.com/assets/2439413/6941123/d61c0572-d84a-11e4-8c25-2b5b523e7595.png)

**Comment by rossdylan** [comment]
+1 this is really killing my profiles workflow.

**Comment by JDrit** [comment]
Closed, could not reproduce since I use an actual web browser
