### ISSUE TITLE
Display failed members as such

### ISSUE THREAD

**Issue by dgonyeo** [JDrit/profiles#31]
If someone's shell is set to `/bin/noshell`, instead of calling them an "Inactive off-floor" call them a "Failed Member" or something similar

**Comment by JDrit** [comment]
I will do this by checking to see if the user is in the `cron` group since that is more widely supported for users. CSH needs some better tracking for failed members though. The change will be easily modified so that it can be changed once we have better tracking for failed members.

**Comment by JDrit** [comment]
closing since cannot be done without a lot of LDAP modifications.

**Comment by JDrit** [comment]
fix ldap

**Comment by JDrit** [comment]
fix ldap

**Comment by JDrit** [comment]
This cannot be done without cleaning up LDAP

**Comment by JDrit** [comment]
This cannot be done without cleaning up LDAP
