### ISSUE TITLE
Cache issue with profile image

### ISSUE THREAD

**Issue by audiolion** [JDrit/profiles#46]
![image](https://user-images.githubusercontent.com/2430381/34278492-292b26a0-e679-11e7-8f15-e3bf9c6a1b48.png)

Logged into profiles today and got this. Seems to be a caching issue, when I go to other pages like "My Profile" it updates to the correct photo.

**Comment by JDrit** [comment]
this was due to a large amount of caching for page responses due to how slow LDAP was at the time. I removed the caching on those pages and the issue has now been fixed. LDAP query times hover around 300ms - 400ms which is not great but manageable.
